# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on: [push, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
      - name: Get code
      - uses: actions/checkout@v1
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
          

          
        
